spring:
  application:
    name: gateway-api
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: gateway-api
            client-name: gateway-api
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI}
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      enabled: true
      cache:
        enabled: true
        ttl: 5s
    gateway:
      server:
        webmvc:
          routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/profiles/**
          - id: user-service-auth
            uri: lb://user-service
            predicates:
              - Path=/api/v1/authorize/**
          - id: wishlist-service
            uri: lb://wishlist-service
            predicates:
              - Path=/api/v1/wishlists/**
          - id: discovery-service
            uri: http://discovery-service:9031
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: discovery-service-static
            uri: http://discovery-service:9031
            predicates:
              - Path=/eureka/**
server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG